---
title: "Persstatistiek"
output:
  pdf_document: default
  html_document: default
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Installing and loading packages
  pkg <- installed.packages()[, "Package"]
  to.load <- c("RColorBrewer", "knitr", "ggplot2", "readxl")
  for (load in to.load) {
      if(!(load %in% pkg)) {
        install.packages(load, dependencies=TRUE)
      }
      library(load, character.only = TRUE )
  }
  
```

## Input
```{r echo = FALSE}
fileInput("Path", 
          "Locatie van Excel document:", 
          multiple = FALSE, 
          accept = c(".xls", ".xlsx"), 
          width = 900, 
          placeholder = "No file selected")

selectInput("rapport", 
            "Selecteer kwartaal:", 
            choices = c("Q1", "Q2", "Q3", "Q4", "Jaar"), 
            selected = "Q1")
```


```{r load_excel, echo=FALSE}
Excel <- read_excel("D:/Documenten/GitHub/Persstatistiek/Persstatistiek_2019.xlsx",
                    sheet = "Hele organisatie")

for (i in c("Kwartaal", "Verzender", "Pu bij Pb", "Persreturn", "Alleen web", "TV", "Beleid", "Detail beleid", "Soort", "Maand")) ({
          Excel[[i]] <- as.factor(Excel[[i]])
      })

# summary(Excel$Kwartaal)
# summary(Excel$Verzender)
# summary(Excel$"Pu bij Pb")
# summary(Excel$Persreturn)
# summary(Excel$"Alleen web")
# summary(Excel$TV)
# summary(Excel$Beleid)
# summary(Excel$"Detail beleid")
# summary(Excel$Soort)
# summary(Excel$Maand)



#renderTable({
#    Excel <- read_excel(input$Path,
#                        sheet = "Hele Organisatie")
#})
```

```{r fix_mistakes, include=FALSE}
if (exists("Excel")) {
    Excel$Beleid <- gsub("Vrije tijd",
                         "Vrije Tijd",
                         Excel$Beleid, ignore.case = FALSE)
    Excel$Beleid <- gsub("Onderwijs en educatie", 
                         "Onderwijs en Educatie", 
                         Excel$Beleid, ignore.case = FALSE)
}
```

```{r split_kwartaal, include=FALSE}
if (exists("Excel")) {
    Persstatistiek <- split.data.frame(Excel, Excel$Kwartaal)
    
    for (i in Persstatistiek) ({
      Persstatistiek[[i]] <- data.frame(Persstatistiek[[i]])
    })
    
    View(Persstatistiek)
    Persstatistiek$Jaar <- Excel
}
```

## Persreturn per beleid

```{r return_per_beleid, echo=FALSE}
renderPlot({
    # Create dataframe for barplot & rename columns
    return.beleid <- data.frame(table(Persstatistiek[[input$rapport]]$Beleid,
                                      Persstatistiek[[input$rapport]]$Persreturn))
    colnames(return.beleid) <- c("Beleid", "Persreturn", "Freq")
    
    # Create barplot
    colors <- brewer.pal(6,"Pastel1")
    ggplot(data=return.beleid, aes(x=Beleid, y=Freq, fill=Persreturn)) + 
            geom_bar(position = "dodge", stat='identity') +
            xlab("Beleid") +
            ylab("Aantal") +
            ggtitle(c("Persreturn per beleid: ", input$rapport)) +
            geom_text(aes(label=Freq), 
                    position=position_dodge(0.9), vjust=0) +
            theme_bw() +
            theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
            scale_fill_manual(values=colors[2:1])  
})


    
```


## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
