---
output: 
  html_document:
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: true
    toc_depth: 3
    number_sections: true
params:
  titel: NA
  # TOCDepth: 3
  ReportSections_Berichten: NA
  ReportSections_Return: NA
  Persberichten.alg: NA
  Persconferenties.alg: NA
  Persberichten.beleid.maand: NA
  Persberichten.beleid.beleid: NA
  Persberichten.verzender.alg: NA
  Persberichten.verzender.maand: NA
  Persberichten.verzender.beleid: NA
  Persberichten.type: NA
  Persreturn.beleid: NA
  Persreturn.medium: NA
  rendered_by_shiny: FALSE
  
title: "`r params$titel`"
author: "Provincie Antwerpen - Persdienst"
date: "`r format(Sys.Date(), '%d %B %Y')`"
---
<!-- Document settings -->
```{r "settings", include = FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, results='asis')
level <- 1
progress <- 0
```

<!-- Persberichten: Headers -->
```{r eval=(length(params$ReportSections_Berichten)>0)}
cat(strrep('#', level), 'Verzonden persberichten \n')
level <- level+1
```

```{r eval=("Berichten" %in% params$ReportSections_Berichten | "Conferenties" %in% params$ReportSections_Berichten)}
cat(strrep('#', level), 'Algemeen provincie \n')
level <- level+1
```

<!-- Persberichten: Algemeen provincie -->
```{r eval="Berichten" %in% params$ReportSections_Berichten }
section <- knitr::knit_child('Section_1_VerzAlgPersberichten.Rmd', quiet=TRUE)
cat(unlist(section), sep= '\n')
```

```{r eval="Conferenties" %in% params$ReportSections_Berichten}
section <- knitr::knit_child('Section_2_VerzAlgPersconferenties.Rmd', quiet=TRUE)
cat(unlist(section), sep= '\n')
```

```{r eval=("Berichten" %in% params$ReportSections_Berichten | "Conferenties" %in% params$ReportSections_Berichten)}
level <- level-1
```

<!-- Persberichten: Per beleid -->
```{r eval="Beleid" %in% params$ReportSections_Berichten }
section <- knitr::knit_child('Section_3_VerzPersberichtenBeleid.Rmd', quiet=TRUE)
cat(unlist(section), sep= '\n')
```

<!-- Persberichten: Per verzender -->
```{r eval=("VerzenderAlg" %in% params$ReportSections_Berichten | "VerzenderBeleid" %in% params$ReportSections_Berichten)}
cat(strrep('#', level), 'Per verzender \n')
level <- level+1
```

```{r eval="VerzenderAlg" %in% params$ReportSections_Berichten }
section <- knitr::knit_child('Section_4_VerzPersberichtenVerzenderAlg.Rmd', quiet=TRUE)
cat(unlist(section), sep= '\n')
```

```{r eval="VerzenderBeleid" %in% params$ReportSections_Berichten }
section <- knitr::knit_child('Section_5_VerzPersberichtenVerzenderBeleid.Rmd', quiet=TRUE)
cat(unlist(section), sep= '\n')
```

```{r eval=("VerzenderAlg" %in% params$ReportSections_Berichten | "VerzenderBeleid" %in% params$ReportSections_Berichten)}
level <- level-1
```

<!-- Persberichten: Per Type -->
```{r eval="Type" %in% params$ReportSections_Berichten }
section <- knitr::knit_child('Section_6_VerzPersberichtenType.Rmd', quiet=TRUE)
cat(unlist(section), sep= '\n')
```

<!-- Persberichten: Headers -->
```{r eval=(length(params$ReportSections_Berichten)>0)}
level <- level-1
```

<!-- Persreturn: Headers -->
```{r eval=(length(params$ReportSections_Return)>0)}
cat(strrep('#', level), 'Persreturn \n')
level <- level+1
```

<!-- Persreturn: Per Beleid -->
```{r eval="Beleid" %in% params$ReportSections_Return }
section <- knitr::knit_child('Section_7_ReturnBeleid.Rmd', quiet=TRUE)
cat(unlist(section), sep= '\n')
```

<!-- Persreturn: Per Medium -->
```{r eval="Medium" %in% params$ReportSections_Return }
section <- knitr::knit_child('Section_8_ReturnMedium.Rmd', quiet=TRUE)
cat(unlist(section), sep= '\n')
```


