---
output: 
  html_document:
    number_sections: true
---

<!-- Document settings -->
```{r include = FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, results='asis')
```

<!-- Section header -->
```{r}
cat(strrep('#', level), 'Persconferenties \n')
level <- level+1
```

<!-- Persconferenties per kwartaal -->
```{r "Persconferenties per kwartaal", result='asis'}
elements <- list(
    tabheader = 'Persconferenties per kwartaal',
    amount = Persconferenties.alg$kwartaal.plot.aantal(),
    percent = Persconferenties.alg$kwartaal.plot.procent(),
    table = Persconferenties.alg$kwartaal.tabel(),
    table_caption = "Persconferenties per kwartaal",
    explanation = Persconferenties.alg$kwartaal.uitleg()
  )
section <- knitr::knit_child('PlotsAndTables.Rmd', quiet=TRUE)
cat(unlist(section), sep= '\n')
```

<!-- Persconferenties per maand -->
```{r "Persconferenties per maand", result='asis'}
elements <- list(
    tabheader = 'Persconferenties per maand',
    amount = Persconferenties.alg$maand.plot.aantal(),
    percent = Persconferenties.alg$maand.plot.procent(),
    table = Persconferenties.alg$maand.tabel(),
    table_caption = "Persconferenties per maand",
    explanation = Persconferenties.alg$maand.uitleg()
  )
section <- knitr::knit_child('PlotsAndTables.Rmd', quiet=TRUE)
cat(unlist(section), sep= '\n')
```

<!-- Persconferenties per week -->
```{r "Persconferenties per week", result='asis'}
elements <- list(
    tabheader = 'Persconferenties per week',
    amount = Persconferenties.alg$week.plot.aantal(),
    percent = Persconferenties.alg$week.plot.procent(),
    table = Persconferenties.alg$week.tabel(),
    table_caption = "Persconferenties per week",
    explanation = Persconferenties.alg$week.uitleg()
  )
section <- knitr::knit_child('PlotsAndTables.Rmd', quiet=TRUE)
cat(unlist(section), sep= '\n')
```

<!-- Persconferenties per dag -->
```{r "Persconferenties per dag", result='asis'}
elements <- list(
    tabheader = 'Persconferenties per dag',
    amount = Persconferenties.alg$dag.plot.aantal(),
    percent = Persconferenties.alg$dag.plot.procent(),
    table = Persconferenties.alg$dag.tabel(),
    table_caption = "Persconferenties per dag",
    explanation = Persconferenties.alg$dag.uitleg()
  )
section <- knitr::knit_child('PlotsAndTables.Rmd', quiet=TRUE)
cat(unlist(section), sep= '\n')
```

<!-- Persconferenties per beleid -->
```{r "Persconferenties per beleid", result='asis'}
elements <- list(
    tabheader = 'Persconferenties per beleid',
    amount = Persconferenties.alg$beleid.plot.aantal(),
    percent = Persconferenties.alg$beleid.plot.procent(),
    table = Persconferenties.alg$beleid.tabel(),
    table_caption = "Persconferenties per beleid",
    explanation = Persconferenties.alg$beleid.uitleg()
  )
section <- knitr::knit_child('PlotsAndTables.Rmd', quiet=TRUE)
cat(unlist(section), sep= '\n')
```

```{r}
level <- level-1
```

